# Generated by Django 4.2.3 on 2026-07-20 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0006_alter_comentario_usuario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria_articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulos.categoria'),
        ),
    ]
